

export default  {
    searchPage:{
        btn:{
            buttonTypes:[
                {code:"search",name:"搜索"},
                {code:"create",name:"新增"},
                {code:"download",name:"下载"},
                {code:"update",name:"更新"},
                {code:"remove",name:"删除"},
                {code:"approve",name:"审核"},
                {code:"reject",name:"拒绝"},
                {code:"start",name:"启用"},
                {code:"stop",name:"停用"},
                {code:"info",name:"详情"},
                {code:"reset",name:"重置"},
                {code:"up",name:"上架"},
                {code:"down",name:"下架"},
                {code:"publish",name:"发布"},
                {code:"cancelPublish",name:"取消发布"},
                {code:"import",name:"导入"},
                {code:"export",name:"导出"},
                {code:"review",name:"批量操作"},
                {code:"copy",name:"复制"},
                {code:"setting",name:"设置"},
                {code:"decorate",name:"装修"},
                {code:"prevPage",name:"上一页"},
                {code:"nextPage",name:"下一页"},
                {code:"confirm",name:"确定"},
                {code:"save",name:"保存"},
                {code:"back",name:"返回"},
                {code:"cancel",name:"取消"},
                {code:"choose",name:"请选择XXXX"},
                {code:"holdSave",name:"暂存"},
                {code:"prev",name:"上一步"},
                {code:"next",name:"下一步"},
                {code:"default",name:"默认"},
                {code:"warning",name:"警告"},
            ],
            defaultBtnPropertys:{
                btnName:"",
                btnType:"",
                btnHandle:"",
                buttonTypes:[]
            }
        },
        col:{
            fieldTypes:[
                {name:"text",code:"text"},
                {name:"select",code:"select"},
                {name:"radioList",code:"radioList"},
                {name:"checkboxList",code:"checkboxList"},
                {name:"datepicker",code:"datepicker"},
                {name:"timepicker",code:"timepicker"},
                {name:"dateTimepicker",code:"dateTimepicker"}
            ],
            defaultColPropertys:{
                fieldTypes:[],
                type:"text",
                key:"",
                label:"",
                labelWidth:"",
                url:"",
                dataSource:"",
                displayName:"",
                displayValue:"",
            }
        }
    },
    dialog:{
        dataSource:[{name:'',code:"1"}]
    },
    fileTypes:{
        dataSource:[{name:"列表页",code:"1"},{name:"save页",code:"2"}],
    },
    form:{
        defaultCol:{
            type:"text",
            key:"",
            label:"",
            labelWidth:"",
            placeholder:"",
            url:"",
            dataSource:"",
            displayName:"",
            displayValue:"",            
            tip:"",
            on:"",
            required:"",
            valifyType:"",
            msg:"",
            selectDataSource:{
                typeDatsSource:[],
                requiredDatsSource:[],
                onDataSource:[],
                valifyDataSource:[]
            }
        }
    },
    enum:{
        typeDatsSource:[
            {name:"text",code:"text"},
            {name:"select",code:"select"},
            {name:"radioList",code:"radioList"},
            {name:"checkboxList",code:"checkboxList"},
            {name:"asynTree",code:"asynTree"},
            {name:"textarea",code:"textarea"},
            {name:"upload",code:"upload"},
            {name:"datepicker",code:"datepicker"},
            {name:"timepicker",code:"timepicker"},
            {name:"dateTimepicker",code:"dateTimepicker"}
        ],
        valifyDataSource:[
            {name:"数字或小数",code:"decimals"},
            {name:"数字",code:"number"},
            {name:"email",code:"email"},
            {name:"url",code:"url"},
            {name:"id",code:"身份证"},
            {name:"phone",code:"手机号"},
            {name:"password",code:"密码"},
            {name:"正整数",code:"positive"},
            {name:"正小数",code:"positiveDecimals"},
            {name:"负小数",code:"negativeDecimals"},
            {name:"负数",code:"negative"},
            {name:"汉字",code:"characters"}
        ],
        requiredDatsSource:[
            {name:'是',code:"1"},
            {name:'否',code:"0"}
        ],
        onDataSource:[
            {name:'是',code:"1"},
            {name:'否',code:"0"}
        ],
        layoutList:[
            {name:"是",code:"1"}
        ]
    },
    webpackProxyConfig:{
        key:"",
        url:"",
    }
}